### ISSUE TITLE
Dark Theme 

### ISSUE THREAD

**Issue by sparklyballs** [dave-p/TVHadmin#14]
Would it be possible to have a dark theme made for this ?

**Comment by dave-p** [comment]
It looks pretty straightforward. Create a new version of style.css with new colour values for the various elements, the code can then select which file to load based on a configuration option.

If you can create a new stylesheet with a dark theme I'll certainly consider committing it.

**Comment by dave-p** [comment]
I've created a new branch 'dark-theme' containing a modified stylesheet. The 'timeline' screen doesn't work at present, and not all controls can be themed on all browsers. How does it look?

**Comment by sparklyballs** [comment]
> I've created a new branch 'dark-theme' containing a modified stylesheet. The 'timeline' screen doesn't work at present, and not all controls can be themed on all browsers. How does it look?

I can take a look later, doing the prep for tomorrow’s dinner
Thankfully I’m only in tier 2 for restrictions, so even for just the one day can have something resembling normal Christmas

**Comment by sparklyballs** [comment]
Did have a little go myself yesterday but was having probs getting colours in the right places

**Comment by dave-p** [comment]
The dark-theme branch is now fully functioning, with a config item to select which theme to use. I'm a developer not a graphics designer but it looks reasonably OK to me.

I've also added a dark-theme branch to the Javascript version. It works fine on Firefox and Chromium, but on Waterfox there is a 'flash of unstyled content' (FOUC) when switching or redrawing screens, caused by the stylesheet only being loaded after the javascript begins to run. I doubt there is a way around that.

I'll merge the branch into master when I've finished testing.
